spring:
  #rabbitmq  for auto reflesh config
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  listener:
    simple:
      acknowledge-mode: auto  # 自动ack
      retry:
        enabled: true
        max-attempts: 5
        max-interval: 10000   # 重试最大间隔时间
        initial-interval: 2000  # 重试初始间隔时间
        multiplier: 2 # 间隔时间乘子，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#打开info,health等断点，所以需要添加management.endpoints.web.exposure.include=*配置，其他的不变
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

#----------------------- 其他配置与config无关 ---------

feign:
  httpclient:
    enabled: false
    # 关闭SSL证书校验(默认：开启校验-false)，适用于httpclient和okhttpclient
    disable-ssl-validation: true
  okhttp:
    enabled: true
  client:
    config:
      # 默认配置，启动Ribbon时失效（即启用了服务注册发现机制时）
      default:
        connectTimeout: 3000
        readTimeout: 3000
  # 开启熔断
  hystrix:
    enabled: false

### 请求处理的超时时间
ribbon:
  # 等待请求响应的超时时间. 单位：ms
  ReadTimeout: 5000
  # 连接超时时间. 单位：ms
  ConnectTimeout: 1000
  # 是否对所有请求进行失败重试, 设置为 false, 让feign只针对Get请求进行重试.
  OkToRetryOnAllOperations: false
  # Max number of retries on the same server (excluding the first try)
  MaxAutoRetries: 3
  # Max number of next servers to retry (excluding the first server)
  MaxAutoRetriesNextServer: 0