---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lhq.
--- DateTime: 2021/7/18 17:39
---


local result = redis.call('set', KEYS[1], KEYS[2], 'ex', KEYS[3], 'nx')
if result == false then
    return 0
else type(result) == 'table' and result['ok'] == 'OK' then
    return 1
end
return 0
