server:
  port: 8081

##spring Setting
spring:
    application:
        name: mysqldemo
    jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: create
        dialect: org.hibernate.dialect.MySQLDialect
    cache:
      cache-names: users

master-db:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3307/geek?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456

slave1-db:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3307/geek1?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456


### 日志配置
log:
  level: debug