spring:
  application:
    name: springboot-mybatisplus
    # DataSource Config
  datasource:
    # 原始的h2驱动
    driver-class-name: org.h2.Driver
    username: root
    password: test
    # 数据库test已经被用了
    url: jdbc:h2:mem:test2
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql

  h2:
    console:
      enabled: true
      path: /h2

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      column-format: "'%s'"