logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG
spring:
  application:
    name: spring-ai
  ai:
    dashscope:
      api-key: ${DASHSCOPE_KEY:}
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model: qwen-max
      chat:
        options:
          model: qwen-max
    mcp:
      server:
        stdio: true
      client:
        type: SYNC
        root-change-notification: true
        toolcallback:
          enabled: true
        enabled: true
        request-timeout: 30s
        stdio:
          connections:
            amap-maps:
              #mac
              command: npx
              #windows
              #command: npx.cmd
              args:
                - "-y"
                - "@amap/amap-maps-mcp-server"
              env:
                "AMAP_MAPS_API_KEY": "${AMAP_KEY:}"