server:
  port: 8082
  max-http-header-size: 209715200
  tomcat:
      accept-count: 200
      max-connections: 200
      max-http-header-size: 2097152
      
# gateway Actuator API
management:
  endpoint:
    gateway:
      # default value
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

logging:
  level:
    org.springframework: debug

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  kafka:
    bootstrap-servers: localhost:19092

debezium:
  mysql:
    hostname: localhost
    port: 3306
    user: root
    password:
    server-name: vhr-server
    database-name: test
    table-include-list: test.t_test,test.log_access
  topic-prefix: test
