server:
  port: 8081

spring:
  application:
    name: shenyu-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    #url: jdbc:mysql://www.lhqmm.com:3306/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    #username: demo
    #password: demo@qaz
    hikari:
      maximum-pool-size: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      minimum-idle: 5

shenyu:
  register:
    registerType: nacos #http #zookeeper #etcd #nacos #consul
    serverLists: http://localhost:9095 #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
  client:
    springCloud:
      props:
        contextPath: /springcloud
        port: 8884

logging:
  level:
    root: info
    org.apache.shenyu: debug