server:
  port: 8081
logging:
  level:
    root: info
    org.springframework.beans: info
    com.example: debug
    com.nydia: debug

spring:
  datasource:
    #url: jdbc:h2:mem:mydb
    url: jdbc:h2:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

id:
  zk:
    url: 192.168.137.100:2181
    sessionTimeoutMs: 15000
    connectionTimeoutMs: 15000
  start: 5000