server:
  port: 8082
  max-http-header-size: 209715200
  tomcat:
      accept-count: 200
      max-connections: 200
      max-http-header-size: 2097152
      
# gateway Actuator API
management:
  endpoint:
    gateway:
      # default value
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

logging:
  level:
    org.springframework: debug

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: