spring:
  profiles:
    active: dev 
    #指定为开发环境

#rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /

#是否开启基本的鉴权，默认为true
security:
  basic:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

testnihao: testNo888