server:
  port: 9000
  servlet:
    context-path: /

spring:
  application:
    name: springboot-elasticsearch

  elasticsearch:
    uris: https://127.0.0.1:9200
    connection-timeout: 5s
    socket-timeout: 10s
    username: elastic
    password: dasdfasfafd
    env: dev