spring:
  application:
    name: springboot-mybatisplus
  datasource:
    url: jdbc:mysql://localhost:3307/ebooks?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
