spring:
  application:
    name: springboot-rabbitmq
  rabbitmq:
    host: 192.168.1.25
    port: 5672
    username: admin
    password: admin
    virtual-host: admin_vhost
  cloud:
    stream:
      function:
        definition: produceMessage;consumeMessage
      bindings:
        produceMessage-out-0:
          destination: myExchange
          content-type: application/json
        consumeMessage-in-0:
          destination: myExchange
          group: myGroup